"""Convert premotion_joints.json into the controller's C++ trajectory table."""

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
INPUT_PATH = ROOT / "premotion_joints.json"
HEADER_PATH = ROOT / "example/walking/src/premotion_targets.hpp"

ARM_JOINTS = [
    "left_shoulder_pitch_joint",
    "left_shoulder_roll_joint",
    "left_shoulder_yaw_joint",
    "left_elbow_joint",
    "left_wrist_roll_joint",
    "left_wrist_pitch_joint",
    "left_wrist_yaw_joint",
    "right_shoulder_pitch_joint",
    "right_shoulder_roll_joint",
    "right_shoulder_yaw_joint",
    "right_elbow_joint",
    "right_wrist_roll_joint",
    "right_wrist_pitch_joint",
    "right_wrist_yaw_joint",
]


def main() -> None:
    trajectory = json.loads(INPUT_PATH.read_text())
    if trajectory["joint_names"] != ARM_JOINTS:
        raise ValueError("premotion joint order does not match the controller")

    waypoints = trajectory["waypoints"]
    if not waypoints:
        raise ValueError("premotion trajectory has no waypoints")
    if any(len(waypoint["arm_joint_positions"]) != len(ARM_JOINTS)
           for waypoint in waypoints):
        raise ValueError("premotion waypoint has an invalid joint count")

    duration = float(trajectory["duration_s"])
    sample_dt = float(trajectory["dt_s"])
    expected_duration = sample_dt * len(waypoints)
    if abs(duration - expected_duration) > 1.0e-6:
        raise ValueError(
            f"duration_s {duration} does not match {len(waypoints)} samples "
            f"at dt_s {sample_dt}"
        )

    rows = []
    for waypoint in waypoints:
        values = ", ".join(
            f"{float(value):.9f}f"
            for value in waypoint["arm_joint_positions"]
        )
        rows.append(f"    {{{{{values}}}}},")

    HEADER_PATH.write_text(
        "#pragma once\n\n"
        "#include <array>\n\n"
        "// Generated by generate_premotion_header.py from premotion_joints.json.\n"
        f"constexpr float PREMOTION_DURATION_SECONDS = {duration:.9f}f;\n"
        f"constexpr float PREMOTION_SAMPLE_DT_SECONDS = {sample_dt:.9f}f;\n"
        f"constexpr std::array<std::array<float, {len(ARM_JOINTS)}>, "
        f"{len(waypoints)}> PREMOTION_ARM_TARGETS{{{{\n"
        + "\n".join(rows)
        + "\n}};\n"
    )
    print(f"Wrote {HEADER_PATH} from {len(waypoints)} JSON waypoints")


if __name__ == "__main__":
    main()
